### ISSUE TITLE
找不到 mysql/tools/nkill 文件

### ISSUE THREAD

**Issue by dodozai** [JiYou/openstack-ubuntu-14-04#1]
cp -rf $TOP_DIR/tools/nkill /usr/bin/
cp: cannot stat 'mysql/tools/nkill' :No such file or directory

**Comment by JiYou** [comment]
你是手动执行的么？

**Comment by JiYou** [comment]
@dodozai

**Comment by dodozai** [comment]
我先执行了init.sh，然后执行mysql.sh，就出现这个问题了，在您的git文件中的mysql中并没有找到tools/function,自己添加进去后就有这个报错了

**Comment by JiYou** [comment]
一开始是需要做一些准备工作的。如果是做实验的话。建议你看一下视频。
直接手动跑会遇到很多很多的问题。

**Comment by JiYou** [comment]
你应该是跳掉了中间某些步骤。
百度云盘的链接我更新了。你可以看一下

链接: https://pan.baidu.com/s/1gg4SVxzZW4Ltwk7TFXDW0A 密码: kgxs

**Comment by JiYou** [comment]
与书对应的话是OpenStack开源云王者归来－学习视频

**Comment by dodozai** [comment]
好的，谢啦
